version: "3.8"

services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - QDRANT_HOST=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - qdrant
      - ollama
    volumes:
      - .:/app
      - /app/node_modules

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s


  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve && ollama pull nomic-embed-text"]

volumes:
  qdrant_storage:
  ollama_data:
